create table _users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    email      varchar(255),
    password   varchar(255),
    updated_at timestamp(6),
    username   varchar(255)
);


create table refresh_tokens
(
    id          bigint generated by default as identity
        primary key,
    expiry_date timestamp(6) with time zone not null,
    token       varchar(255),
    user_id     bigint
        constraint uk7tdcd6ab5wsgoudnvj7xf1b7l
            unique
        constraint fkfxtp0cyvmiuqdmcw7lfhki3e7
            references _users
);

-- role enum
CREATE TYPE role_type as ENUM ('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN');

create table roles
(
    id   bigint not null
        primary key,
    name role_type unique not null
);


create table user_roles
(
    user_id bigint not null
        constraint fkeu2s2wbtt1hgogjxaf1adv3ij
            references _users,
    role_id bigint not null
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references roles,
    primary key (user_id, role_id)
);

